---
- name: apply network device template
  vars:
    ansible_connection: network_cli
    ansible_become: true
    ansible_become_method: enable
  ansible.netcommon.cli_config:
    config: "{{ lookup('template', 'templates/{{ansible_network_os}}_{{type}}.j2') }}"
