---
- name: Wait for BIG-IP to boot up completely
  wait_for:
    host: "{{ ansible_host }}"
    port: 8443
    state: present

- name: Change BIG-IP F5 mgmt password
  f5networks.f5_modules.bigip_command:
    provider:
      ssh_keyfile: "{{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
      transport: cli
      user: admin
      server: "{{ ansible_host }}"
    commands: "modify auth user admin password {{admin_password}}"
  register: change_password
  until: change_password is not failed
  retries: 5
  delay: 10

- name: Wait for API to be Ready
  f5networks.f5_modules.bigip_wait:
    timeout: 300
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"
  delegate_to: localhost

# The bigip_lx_package requires rpm installed, on macOS use brew rather than pip or it won't work
- name: Install AS3
  f5networks.f5_modules.bigip_lx_package:
    package: "{{playbook_dir}}/../roles/f5_setup/files/f5-appsvcs-3.25.0-3.noarch.rpm"
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"
      timeout: 300
  register: install_as3
  until: install_as3 is not failed
  retries: 2

- name: Set db provision.extramb
  f5networks.f5_modules.bigip_sys_db:
    key: provision.extramb
    value: "1024"
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"

- name: Set db restjavad.useextramb
  f5networks.f5_modules.bigip_sys_db:
    key: restjavad.useextramb
    value: "true"
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"

- name: Set db restjavad.timeout
  f5networks.f5_modules.bigip_sys_db:
    key: restjavad.timeout
    value: "180"
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"

- name: Set httpd max-clients
  f5networks.f5_modules.bigip_device_httpd:
    max_clients: 20
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"

- name: Save Config
  f5networks.f5_modules.bigip_config:
    save: true
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"

- name: Restart REST
  f5networks.f5_modules.bigip_command:
    provider:
      validate_certs: "no"
      user: admin
      password: "{{admin_password}}"
      server_port: 8443
      server: "{{ ansible_host }}"
    commands:
      - restart sys service restjavad
      - restart sys service restnoded
  ignore_errors: true
