---
- name: configure f5 workshops for webservers node1 and node2
  hosts: lab_hosts
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: "{{ playbook_dir }}/../roles/webservers"

- name: setup f5 nodes
  hosts: f5
  become: false
  connection: local
  gather_facts: false
  tasks:
    - include_role:
        name: "{{ playbook_dir }}/../roles/f5_setup"
